### ISSUE TITLE
안녕하세요 몇 가지 질문사항이 있습니다.

### ISSUE THREAD

**Issue by Foreist** [warnikchow/raws#3]
저번에 케라스 단톡방에서 문의드렸던 사람입니다.
몇 가지 문의사항이 있어서 연락드렸는데요.
csct가 세 가지인데 이 중에서 csct_train으로 기학습된 임베딩데이터를  넣고 학습을 하는 것 같은데 faxtext로 corpus를 임베딩하실 때는 띄어쓰기가 잘된 말뭉치로 임베딩하신 게 전부인가요?
그리고 csct_train 12번째 줄에서 drama_total_cor.txt라고 있는데 해당 파일은 임베딩되기 전 corpus를 넣으신 건지가 궁금합니다!

**Comment by warnikchow** [comment]
네 csct_train을 메인으로 참고하시면 되고, 띄어쓰기가 잘 된 말뭉치 자체가 이미 각 음절에 대한 label이 되어있다고 볼 수 있기 때문입니다. 다른 두 파일은 데모 용입니다.

해당 부분은 제가 가진 드라마 코퍼스를 학습 데이터로 활용하여 그렇지만, 이론상 띄어쓰기가 잘 되어 있는 어떤 코퍼스를 사용하셔도 문제가 없습니다. 임베딩 전의 raw text를 넣는 것이 맞습니다. raw text를 읽어서 한 line (문장)을 하나의 string으로 보고, 각 음절(blank 포함)을 한 entry 로 취급하시면 됩니다.

**Comment by Foreist** [comment]
감사합니다 해당 이슈는 종료하도록 하겠습니다!
